Begin translating the introduction.
vuejs-sv/vuejs.org pull request #11
Opened 2019-07-10 22:39 UTC by sustained

109/404 lines complete.

2019-07-15 12:37 UTC, Pwntus requested changes
Bli inte förtvivlad även om det är många requested changes, det är fortfarande bra jobbat! :+1:

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Vue (uttalas /vjuː/ såsom **view** i engelskan) är ett **progressivt ramverk** för att bygga användargränssnitt. Till skillnad från andra monolitiska ramverk designas Vue från början så att det kan s
`fokuserar på bara presentationen` :arrow_right: `fokuserar endast på prestationen`
Byt ut `och` med ett komma här: `och är enkelt att komma igång med...` :arrow_right: `, är enkelt att komma igång med...` (undvik flera **och** efter varandra men sätt ett på slutet efter flera komma-tecken)
`förmåga` :arrow_right: `förmågan`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Om du skulle vilja lära dig mer om Vue innan vi kommer igång då <a id="modal-player"  href="#">titta på denna video</a> som ska gå igenom grunderna med ett provprojekt.
`...titta då på denna video som går igenom grunderna`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +<p class="tip">Den officiella guiden förmodar en mellanliggande kunskapsnivå på HTML, CSS och Javascript. Om du är helt ny till frontend utveckling då bör du nog inte försöka lära dig ett ramverk för
Jag skulle byta ut `...kunskapsnivå på HTML...` till `...kunskapsnivå med HTML...`, men är lite osäker själv här (kanske **i HTML** t.o.m.).
`frontend utveckling` :arrow_right: `frontenduntveckling/frontend-utveckling`.
Ta bort **då** här: `då bör du nog...` :arrow_right: `bör du nog...` (eller lägg ett komma före **då**).

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Det enklaste sättet att pröva Vue.js är att använda vårt [JSFiddle Hello World example](https://jsfiddle.net/chrisvfritz/50wL7mdz/). Öppna gärna det i en ny flik och följ med medan vi går igenom någr
`inkluderar` :arrow_right: `inkludera`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +<!-- "production" version, optimerad for storlek och hastighet -->
`produktionsversion`
`utvecklingsutgåvan/produktionsutgåvan av Vue` är kanske bättre för "development/production version of Vue", och `utvecklingsläge/produktionsläge i Vue` för "development/production mode in Vue".

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +[Installationssidan](installation.html) ger fler alternativ för att installera Vue. **Obs.** Vi **rekommenderar inte** att nybörjare börjar med `vue-cli`, särskilt om inte man är bekant med Node.js-b
`...om inte man är...` :arrow_right: `...om man inte är...`
`Node.js-baserat` :arrow_right: `Node.js-baserade` (plural)

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +<div class="scrimba"><a href="https://scrimba.com/p/pXKqta/cQ3QVcr" target="_blank" rel="noopener noreferrer">Pröva denna lektion på Scrimba</a></div>
`Pröva` :arrow_right: `Prova`, "pröva" låter mer som om du utsätter Scrimbalektionen för _en prövning_ :smile:

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Vid Vues kärna ligger ett system som gör det möjligt att rendera deklarativt data till dokumentobjektmodellen (härefter DOM:n) via en rätt så enkel mallsyntax:
Flippa `rendera deklarativt` :arrow_right: `deklarativt rendera`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Därmed har vi skapat vår första Vue-app! Det liknar alldeles att rendera en strängmall men Vue har gjort mycket arbete i bakgrunden. Datan och DOM:n är kopplade och allt är **reaktivt**. Hur vet man?
`Det liknar alldeles att rendera en strängmall men` :arrow_right: `Detta kan liknas vid att rendera en strängmall`
`Hur vet man?` :arrow_right: `Hur vet man det?`
`till en annan värde` :arrow_right: `till ett annat värde`
Lägg ett **att** här: `Således ser du att exemplet uppdateras`.

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Dessutom "text interpolation" kan vi binda element-attributer så här:
`Dessutom "text interpolation"` :arrow_right:  `Utöver textinterpolering`
`element-attributer` :arrow_right:  `element-attribut` (ett attribut, flera attribut)

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Här har vi stött på något nytt. `v-bind`-attributen som du ser ovan heter ett **direktiv** (directive). Direktiv börjar med `v-` för att tyda på att de är speciella attributer som ges av Vue och som
`heter ett **direktiv**` :arrow_right: `kallas **direktiv**` (plural)
`attributer` :arrow_right: `attribut`
Lägg till komma: `...Vue och som du kanske har gissat tillämpar...` :arrow_right: `...Vue, och som du kanske har gissat, tillämpar...`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +<div class="scrimba"><a href="https://scrimba.com/p/pXKqta/cEQe4SJ" target="_blank" rel="noopener noreferrer">Pröva denna lektion på Scrimba</a></div>
`Pröva` :arrow_right: `Prova`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Det är lätt att ändra en elements närvaro också:
`Det är också lätt att ändra närvaron av ett element:`
Dessa meningar kan vara knepiga då ord kastas runt.

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +## Villkor och slingar
`slingar` :arrow_right: `slingor`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Varsågod ange `app3.seen = false` i webbkonsolen. Du ska se att meddelandet försvinner.
`Varsågod ange` :arrow_right: `Skriv nu` ("varsågod ange..." blir mera "you're welcome to...", och "var god ange..." är för formellt).
`Du ska se att meddelandet försvinner` :arrow_right: `Meddelandet bör försvinna`.

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Det här exemplet bevisar att vi kan binda data till inte bara text och attributer utan även själva strukturen av DOM:n. Dessutom ger Vue ett kraftfull transition-system som kan automatiskt applicera
`bevisar` :arrow_right: `visar/demonstrerar`
`attributer` :arrow_right: `attribut`
`ett kraftfull` :arrow_right: `ett kraftfullt`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +      { text: 'Bygger nåt fantastiskt' }
`Bygger nåt fantastiskt` :arrow_right: `Bygg nåt fantastiskt`
Exempelkod som inte är så viktigt.

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +<div class="scrimba"><a href="https://scrimba.com/p/pXKqta/czPNaUr" target="_blank" rel="noopener noreferrer">Pröva denna lektion på Scrimba</a></div>
Pröva :arrow_right: `Prova`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +I avsikt att låta användare interagerar med din app kan vi använda `v-on`-direktivet för att attach event listeners (TRANSLATE!) som anropar metoder på våra Vue-instanser:
`interagerar` :arrow_right: `interagera`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +<div class="scrimba"><a href="https://scrimba.com/p/pXKqta/cEQVkA3" target="_blank" rel="noopener noreferrer">Pröva denna lektion på Scrimba</a></div>
`Pröva` :arrow_right: `Prova`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Komponentssystemet är ett till viktigt begrepp i Vue därför att det är an abstraktion som låter oss bygga storskaliga applikationer som sammansätts (TRANSLATE?) av små, fristående och oftast återanvä
`är ett till viktigt` :arrow_right: `är även ett viktigt`
`därför att det är an` :arrow_right: `p.g.a. att det är en`
`komponentsträd` :arrow_right: `komponentträd` (yes, two **t**'s)

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +![Komponentsträdet](/images/components.png)
`Komponentsträdet` :arrow_right: `Komponentträdet`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Nu kan den används i en annan komponents mall:
`används i en annan komponents mall` :arrow_right: `användas i en mall i en annan komponent`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Men detta skulle rendera samma text för varje todo (TRANSLATE?) vilket inte är särskilt intresserande. Vi skulle kunna skicka data från the parent scope (TRANSLATE!) in i child components (TRANSLATE!
`intresserande` :arrow_right: `intressant`
`komponentsdefinitionen` :arrow_right: `komponentdefinitionen`
`ska ta` :arrow_right: `tar`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +  // Denna attribut heter todo.
`Denna attribut` :arrow_right: `Detta attribut`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +      -objekten. Vi bindar då varje todo-items todo-egenskap
`bindar` :arrow_right: `binder`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +      Varje komponent behövs också en nyckel (TRANSLATE?) som
`behövs` :arrow_right: `behöver`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Detta är ett konstlat exempel men vi har lyckats skilja vår app in i två mindre enheter och barnet (TRANSLATE?) är relativt decoupled (TRANSLATE!) från föräldern via egemskapsgränssnittet (TRANSLATE?
`påverkar` :arrow_right: ` påverka`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Du kanske lagt märke till att Vue-komponenter liknar mycket **Custom Elements**, som tillhör [Web Components Spec](https://www.w3.org/wiki/WebComponents/). Det är på grund av att Vues komponentsyntax
`T.ex` :arrow_right: `T.ex.` (punkt)
`genomför` :arrow_right: `implementerar` (i denna context)
`den speciella is-attributen` :arrow_right: `det speciella is-attributet`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +1. The Web Components Spec (TRANSLATE!) har slutföras men är inte natively implemented (TRANSLATE!) i varje webbläsare. Safari 10.1+, Chrome 54+ och Firefox 63+ natively (TRANSLATE!) stödjer webbkomp
`slutföras` :arrow_right: `slutförts`
`in en` :arrow_right: `in i en`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +2. Vue-komponenter ger viktiga fuktioner som inte är tillgängliga med enkla custom (TRANSLATE!) element. Sådana som tvärskomponent dataflöde, custom (TRANSLATE!) händelsekommunikation och byggverktyg
`tvärskomponent dataflöde` :arrow_right: `dataflöde på tvärs av komponenter`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Fastän Vue använder ej custom (TRANSLATE!) element internt har det [great interoperability](https://custom-elements-everywhere.com/#vue) (TRANSLATE!) när det gäller att förbruka eller fördela som cus
`använder ej` :arrow_right: `ej använder`
`förbruka eller fördela som` :arrow_right: `förbrukas eller fördelas`

2019-07-15 12:37 UTC, Pwntus commented on src/v2/guide/index.md
> +Vi har presenterat kortfattat Vues grundfunktioner - resten av den här guiden ska beskriva dem och andra avancerade funktioner in i minsta detalj, så se till att du läsa igenom den!
`presenterat kortfattat` :arrow_right: `kortfattat presenterat`
`läsa` :arrow_right: `läser`

2019-07-16 17:36 UTC, sustained commented
Changes incoming.

2019-07-16 17:46 UTC, sustained commented on src/v2/guide/index.md
> +Vue (uttalas /vjuː/ såsom **view** i engelskan) är ett **progressivt ramverk** för att bygga användargränssnitt. Till skillnad från andra monolitiska ramverk designas Vue från början så att det kan s
Ursäkta men betyder inte `prestation` "performance"?

2019-07-16 17:50 UTC, sustained commented on src/v2/guide/index.md
> +Vue (uttalas /vjuː/ såsom **view** i engelskan) är ett **progressivt ramverk** för att bygga användargränssnitt. Till skillnad från andra monolitiska ramverk designas Vue från början så att det kan s
I have however fixed the rest.

2019-07-16 17:50 UTC, sustained commented on src/v2/guide/index.md
> +Om du skulle vilja lära dig mer om Vue innan vi kommer igång då <a id="modal-player"  href="#">titta på denna video</a> som ska gå igenom grunderna med ett provprojekt.
Fixed!

2019-07-16 17:52 UTC, sustained commented on src/v2/guide/index.md
> +<p class="tip">Den officiella guiden förmodar en mellanliggande kunskapsnivå på HTML, CSS och Javascript. Om du är helt ny till frontend utveckling då bör du nog inte försöka lära dig ett ramverk för
Changed to `i` because `kunskap i` is much more common than `kunskap med`, I looked it up.

2019-07-16 17:52 UTC, sustained commented on src/v2/guide/index.md
> +<p class="tip">Den officiella guiden förmodar en mellanliggande kunskapsnivå på HTML, CSS och Javascript. Om du är helt ny till frontend utveckling då bör du nog inte försöka lära dig ett ramverk för
Fixed!

2019-07-16 17:55 UTC, sustained commented on src/v2/guide/index.md
> +<!-- "production" version, optimerad for storlek och hastighet -->
Fixed!

2019-07-16 17:57 UTC, sustained commented on src/v2/guide/index.md
> +[Installationssidan](installation.html) ger fler alternativ för att installera Vue. **Obs.** Vi **rekommenderar inte** att nybörjare börjar med `vue-cli`, särskilt om inte man är bekant med Node.js-b
Does the `om inte` wording not cause it to translate as "unless"? So then without the `särskilt` it would be fine, correct? I'll change it anywho!

2019-07-16 17:58 UTC, sustained commented on src/v2/guide/index.md
> +<div class="scrimba"><a href="https://scrimba.com/p/pXKqta/cQ3QVcr" target="_blank" rel="noopener noreferrer">Pröva denna lektion på Scrimba</a></div>
Alldrig förstod skillnaden även om folk har försökt förklara om och om igen. Fixat!

2019-07-16 17:59 UTC, sustained commented on src/v2/guide/index.md
> +Vid Vues kärna ligger ett system som gör det möjligt att rendera deklarativt data till dokumentobjektmodellen (härefter DOM:n) via en rätt så enkel mallsyntax:
Fixed!

2019-07-16 18:00 UTC, sustained commented on src/v2/guide/index.md
> +Därmed har vi skapat vår första Vue-app! Det liknar alldeles att rendera en strängmall men Vue har gjort mycket arbete i bakgrunden. Datan och DOM:n är kopplade och allt är **reaktivt**. Hur vet man?
Fixed, thanks!

2019-07-16 18:02 UTC, sustained commented on src/v2/guide/index.md
> +Dessutom "text interpolation" kan vi binda element-attributer så här:
Done!

2019-07-16 18:04 UTC, sustained commented on src/v2/guide/index.md
> +Här har vi stött på något nytt. `v-bind`-attributen som du ser ovan heter ett **direktiv** (directive). Direktiv börjar med `v-` för att tyda på att de är speciella attributer som ges av Vue och som
Not "kallas __för__ direktiv"? I've changed it to that because it gets across more the sense of "is known as, is referred to as" which feels better to me here somehow.

2019-07-16 18:05 UTC, sustained commented on src/v2/guide/index.md
> +Här har vi stött på något nytt. `v-bind`-attributen som du ser ovan heter ett **direktiv** (directive). Direktiv börjar med `v-` för att tyda på att de är speciella attributer som ges av Vue och som
Fixed the rest.

2019-07-16 18:05 UTC, sustained commented on src/v2/guide/index.md
> +<div class="scrimba"><a href="https://scrimba.com/p/pXKqta/cEQe4SJ" target="_blank" rel="noopener noreferrer">Pröva denna lektion på Scrimba</a></div>
Gjort!

2019-07-16 18:06 UTC, sustained commented on src/v2/guide/index.md
> +Det är lätt att ändra en elements närvaro också:
Ändrat!

2019-07-16 18:07 UTC, sustained commented on src/v2/guide/index.md
> +## Villkor och slingar
Oh yes, -e -> -ar; -a -> -or!

2019-07-16 18:09 UTC, sustained commented on src/v2/guide/index.md
> +Varsågod ange `app3.seen = false` i webbkonsolen. Du ska se att meddelandet försvinner.
Har förändrat!

2019-07-16 18:10 UTC, sustained commented on src/v2/guide/index.md
> +Det här exemplet bevisar att vi kan binda data till inte bara text och attributer utan även själva strukturen av DOM:n. Dessutom ger Vue ett kraftfull transition-system som kan automatiskt applicera
The word attribute strikes again.

2019-07-16 18:11 UTC, sustained commented on src/v2/guide/index.md
> +Det här exemplet bevisar att vi kan binda data till inte bara text och attributer utan även själva strukturen av DOM:n. Dessutom ger Vue ett kraftfull transition-system som kan automatiskt applicera
It just __feels__ like an en word. I'm telling you, they gave it the wrong gender.

2019-07-16 18:12 UTC, sustained commented on src/v2/guide/index.md
> +      { text: 'Bygger nåt fantastiskt' }
Oops, imperative tense!

2019-07-16 18:13 UTC, sustained commented on src/v2/guide/index.md
> +I avsikt att låta användare interagerar med din app kan vi använda `v-on`-direktivet för att attach event listeners (TRANSLATE!) som anropar metoder på våra Vue-instanser:
Ah yes, of course!

2019-07-16 18:15 UTC, sustained commented on src/v2/guide/index.md
> +Komponentssystemet är ett till viktigt begrepp i Vue därför att det är an abstraktion som låter oss bygga storskaliga applikationer som sammansätts (TRANSLATE?) av små, fristående och oftast återanvä
Compound words are hard.

2019-07-16 18:18 UTC, sustained commented on src/v2/guide/index.md
> +      Varje komponent behövs också en nyckel (TRANSLATE?) som
Yeah, what an odd mistake.

2019-07-16 22:53 UTC, Pwntus commented on src/v2/guide/index.md
> +Vue (uttalas /vjuː/ såsom **view** i engelskan) är ett **progressivt ramverk** för att bygga användargränssnitt. Till skillnad från andra monolitiska ramverk designas Vue från början så att det kan s
Stämmer, det skall vara `presentationen` :+1:

2019-07-16 23:00 UTC, Pwntus commented on src/v2/guide/index.md
> +[Installationssidan](installation.html) ger fler alternativ för att installera Vue. **Obs.** Vi **rekommenderar inte** att nybörjare börjar med `vue-cli`, särskilt om inte man är bekant med Node.js-b
Yes, that's event better. Remove `särskilt` + the comma. So: `...att nybörjare börjar med vue-cli  om inte man är bekant med...`.

2019-07-16 23:09 UTC, Pwntus commented on src/v2/guide/index.md
> +Här har vi stött på något nytt. `v-bind`-attributen som du ser ovan heter ett **direktiv** (directive). Direktiv börjar med `v-` för att tyda på att de är speciella attributer som ges av Vue och som
I don't think it's correct to use **för** in front of the plural noun here (donno if it's a rule or smth but it sounds erroneous).
`kallas för ett direktiv` Ok
`kallas direktiv` Ok
`kallas för direktiv` No

2019-07-16 23:19 UTC, sustained commented on src/v2/guide/index.md
> +Här har vi stött på något nytt. `v-bind`-attributen som du ser ovan heter ett **direktiv** (directive). Direktiv börjar med `v-` för att tyda på att de är speciella attributer som ges av Vue och som
Huh okay, I'll change it.

2019-07-16 23:23 UTC, sustained commented
@Pwntus All fixed, then. Do you think we should be merging things into master after reviews even when there are those `(TRANSLATE!)` and `(TRANSLATE?)` markers present or not?

2019-07-17 15:36 UTC, Pwntus commented
Looks good for merging! Yes I think we'll just merge it with the markers present and make a large PR for when we've established a complete list of translation conventions.

2019-07-17 18:30 UTC, merged